definitions:
  db.Event:
    properties:
      description:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
info:
  title: "Your API Title"
  version: "1.0.0"
  contact:
    name: "Your Name"
    email: "your.email@example.com"
    url: "https://example.com"
paths:
  /events:
    get:
      consumes:
      - application/json
      description: Get a list of all events
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Event'
            type: array
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get events
      tags:
      - events
swagger: "2.0"
