-- CREATE TABLE user (
--   id UUID PRIMARY KEY,
--   first_name VARCHAR(255),
--   last_name VARCHAR(255),
--   zone_id VARCHAR(255),
--   email VARCHAR(255) UNIQUE,
--   phone VARCHAR(255) UNIQUE,
--   street VARCHAR(255),
--   city VARCHAR(255),
--   postal_code VARCHAR(255),
--   iam_id VARCHAR(255) UNIQUE
-- );
