GO_MICRO_SERVICE_PORT : 9020
GO_MICRO_SERVICE_REGISTRY_URL : http://admin:admin@localhost:8761/eureka/apps/
GO_MICRO_RENEWALINTERVALINSEC : 5
GO_MICRO_DURATIONINSECS : 10
GO_MICRO_KEYCLOAK_URL : http://localhost:9080
GO_MICRO_CLIENT_ID : internal
GO_MICRO_CLIENT_SECRET : internal
GO_MICRO_REALM_NAME : jhipster
GO_MICRO_DB_URL : postgresql://backend@localhost:5432/backend
